/* ==========================================================
   Neon Arcade — site logic
   Generated by Gaming Website Structure Builder (original code).

   FULLY DATA-DRIVEN: this file reads games.json and renders
   every game card, category and section automatically.
   To add a game: add an entry to games.json + upload its image
   to /images. You never need to touch this file.

   games.json entry shape:
   { "title": "...", "image": "images/x.jpg", "url": "...",
     "category": "...", "featured": true (optional),
     "trending": true (optional) }
   ========================================================== */
(function () {
  'use strict';

  /* ---- Configuration ---- */
  var PLACEHOLDER = 'images/placeholder.jpg';
  var SECTIONS = ["featured","trending","new","all"]; // section render order

  /* Fallback data — only used if games.json cannot be fetched
     (e.g. previewing the page without a server). */
  var FALLBACK_GAMES = [{"title":"Neon Drift","image":"images/placeholder.jpg","url":"#","category":"Racing","featured":true,"trending":true},{"title":"Pixel Siege","image":"images/placeholder.jpg","url":"#","category":"Action","featured":true,"trending":true},{"title":"Mind Grid","image":"images/placeholder.jpg","url":"#","category":"Puzzle","featured":true},{"title":"Star Vanguard","image":"images/placeholder.jpg","url":"#","category":"Strategy","featured":true,"trending":true}];

  /* ---- State ---- */
  var allGames = [];
  var activeCategory = 'all';
  var searchQuery = '';

  var content = document.getElementById('content');
  var searchInput = document.getElementById('search-input');

  /* ---- 1. Load games.json ---- */
  function loadGames() {
    if (window.__GAMES__) return Promise.resolve(window.__GAMES__); // embedded preview mode
    return fetch('games.json', { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) throw new Error('games.json HTTP ' + r.status);
        return r.json();
      })
      .catch(function (err) {
        console.warn('Could not load games.json, using fallback data:', err);
        return FALLBACK_GAMES;
      });
  }

  /* ---- 2. Filtering helpers ---- */
  function matchesFilters(game) {
    var okCat = activeCategory === 'all' ||
      (game.category || '').toLowerCase() === activeCategory.toLowerCase();
    var okQuery = !searchQuery ||
      (game.title || '').toLowerCase().indexOf(searchQuery) !== -1;
    return okCat && okQuery;
  }

  function isFiltering() {
    return activeCategory !== 'all' || searchQuery !== '';
  }

  /* ---- 3. Card builder ---- */
  function buildCard(game, badge) {
    var card = document.createElement('a');
    card.className = 'game-card';
    card.href = game.url || '#';
    if (game.url && game.url !== '#') card.target = '_blank';
    card.rel = 'noopener';

    var media = document.createElement('div');
    media.className = 'card-media';

    var img = document.createElement('img');
    img.src = game.image || PLACEHOLDER;
    img.alt = game.title || 'Game';
    img.loading = 'lazy'; // fast loading: images load only when near the viewport
    img.onerror = function () { img.src = PLACEHOLDER; }; // broken path -> placeholder
    media.appendChild(img);

    if (badge) {
      var b = document.createElement('span');
      b.className = 'card-badge';
      b.textContent = badge;
      media.appendChild(b);
    }

    var body = document.createElement('div');
    body.className = 'card-body';
    var title = document.createElement('div');
    title.className = 'card-title';
    title.textContent = game.title || 'Untitled';
    var cat = document.createElement('div');
    cat.className = 'card-category';
    cat.textContent = game.category || '';
    body.appendChild(title);
    body.appendChild(cat);

    card.appendChild(media);
    card.appendChild(body);
    return card;
  }

  /* ---- 4. Section builder ---- */
  function buildSection(id, title, games, badgeFn) {
    if (!games.length) return null;
    var section = document.createElement('section');
    section.className = 'section';
    section.id = id;

    var head = document.createElement('div');
    head.className = 'section-head';
    var h2 = document.createElement('h2');
    h2.className = 'section-title';
    h2.textContent = title;
    var count = document.createElement('span');
    count.className = 'section-count';
    count.textContent = games.length + (games.length === 1 ? ' game' : ' games');
    head.appendChild(h2);
    head.appendChild(count);
    section.appendChild(head);

    var grid = document.createElement('div');
    grid.className = 'game-grid';
    games.forEach(function (g) {
      grid.appendChild(buildCard(g, badgeFn ? badgeFn(g) : null));
    });
    section.appendChild(grid);
    return section;
  }

  /* ---- 5. Category bar (built from the categories present in games.json) ---- */
  function buildCategoryBar() {
    var cats = ['all'];
    allGames.forEach(function (g) {
      var c = g.category || 'Other';
      if (cats.indexOf(c) === -1) cats.push(c);
    });

    var bar = document.createElement('div');
    bar.className = 'category-bar';
    cats.forEach(function (c) {
      var pill = document.createElement('button');
      pill.className = 'category-pill' +
        (c.toLowerCase() === activeCategory.toLowerCase() ? ' active' : '');
      pill.textContent = c === 'all' ? 'All Games' : c;
      pill.addEventListener('click', function () {
        activeCategory = c;
        syncNavHighlight();
        render();
      });
      bar.appendChild(pill);
    });
    return bar;
  }

  /* Keep header nav links in sync with the active category */
  function syncNavHighlight() {
    document.querySelectorAll('.nav-link').forEach(function (link) {
      var cat = link.getAttribute('data-category');
      var isActive = (!cat && activeCategory === 'all') ||
        (cat && cat.toLowerCase() === activeCategory.toLowerCase());
      link.classList.toggle('active', !!isActive);
    });
  }

  /* ---- 6. Main render ---- */
  function render() {
    content.innerHTML = '';
    content.appendChild(buildCategoryBar());

    /* When searching or filtering by category, show ONE results grid */
    if (isFiltering()) {
      var results = allGames.filter(matchesFilters);
      var label = searchQuery
        ? 'Results for "' + searchQuery + '"'
        : activeCategory;
      var sec = buildSection('results', label, results);
      if (sec) {
        content.appendChild(sec);
      } else {
        var empty = document.createElement('div');
        empty.className = 'empty-state';
        empty.textContent = 'No games found. Try another search or category.';
        content.appendChild(empty);
      }
      return;
    }

    /* Default homepage: sections in the configured order */
    SECTIONS.forEach(function (key) {
      var sec = null;
      if (key === 'featured') {
        var featured = allGames.filter(function (g) { return g.featured; });
        if (!featured.length) featured = allGames.slice(0, 4); // sensible fallback
        sec = buildSection('featured', 'Featured Games', featured, function () { return 'Featured'; });
      } else if (key === 'trending') {
        var trending = allGames.filter(function (g) { return g.trending; });
        if (!trending.length) trending = allGames.slice(4, 10);
        sec = buildSection('trending', 'Trending Now', trending, function () { return 'Hot'; });
      } else if (key === 'new') {
        sec = buildSection('new', 'New Releases', allGames.slice(-6), function () { return 'New'; });
      } else { // 'all'
        sec = buildSection('all-games', 'All Games', allGames);
      }
      if (sec) content.appendChild(sec);
    });
  }

  /* ---- 7. Wire up header nav (nav items act as category filters) ---- */
  function wireNav() {
    document.querySelectorAll('.nav-link').forEach(function (link) {
      link.addEventListener('click', function (e) {
        e.preventDefault();
        var cat = link.getAttribute('data-category');
        activeCategory = cat || 'all';
        searchQuery = '';
        if (searchInput) searchInput.value = '';
        syncNavHighlight();
        render();
        // Close mobile menu after a choice
        document.getElementById('main-nav').classList.remove('open');
      });
    });

    var toggle = document.getElementById('menu-toggle');
    var nav = document.getElementById('main-nav');
    if (toggle && nav) {
      toggle.addEventListener('click', function () {
        var open = nav.classList.toggle('open');
        toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
      });
    }
  }

  /* ---- 8. Search ---- */
  function wireSearch() {
    if (!searchInput) return;
    searchInput.addEventListener('input', function () {
      searchQuery = searchInput.value.trim().toLowerCase();
      render();
    });
  }

  /* ---- 9. Boot ---- */
  function init() {
    var yearEl = document.getElementById('year');
    if (yearEl) yearEl.textContent = new Date().getFullYear();
    wireNav();
    wireSearch();
    loadGames().then(function (games) {
      allGames = Array.isArray(games) ? games : [];
      render();
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
